! Problem 2: Even Fibonacci Numbers
! Author: Christian Brewer
! Date: 2024-12-15
! Prompt: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first
! 10 terms would be: 1,2,3,5,8,8,13,21,34,55,89... By considering the terms in the Fibonacci sequence whose values do not exceed
! four million, find the sum of the even-valued terms.

program problem_2

        implicit none

        integer :: sum, curr, prev, swap

        sum = 0
        curr = 2
        prev = 1
        swap = 0

        do while (curr < 4000000)
                if (mod(curr, 2) == 0) then
                        sum = sum + curr
                end if
                swap = curr
                curr = curr + prev
                prev = swap
        end do
        print *, sum
end program problem_2
